"""
    This file defines error codes used in factor keeper, you can add new ones if needed.
"""


class Error(object):
    SUCCESS = 0

    ERROR_WORKER_VERSION_DEPRECATED = 1
    ERROR_SERVER_INTERNAL_ERROR = 2
    ERROR_FACTOR_NOT_EXISTS = 3
    ERROR_FACTOR_ALREADY_EXISTS = 4
    ERROR_FACTOR_VERSION_NOT_EXISTS = 5
    ERROR_FACTOR_VERSION_ALREADY_EXISTS = 6
    ERROR_FILE_UPLOAD_FAILED = 7
    ERROR_DB_EXECUTION_FAILED = 8
    ERROR_LINKAGE_NOT_EXISTS = 9
    ERROR_INVALID_TIME_RANGE = 10
    ERROR_FAILED_TO_UPDATE_FACTOR_RESULT = 11
    ERROR_UNRECOGNIZED_FILE_TYPE = 12
    ERROR_FAILED_TO_CREATE_FILE_OR_DIR = 13
    ERROR_FAILED_TO_LOAD_FACTOR_GENERATOR_MODULE = 14
    ERROR_LINKAGE_ALREADY_EXISTS = 15
    ERROR_FACTOR_GENERATE_FAILED = 16
    ERROR_FACTOR_DATETIME_FIELD_NOT_EXISTS = 17
    ERROR_FACTOR_RESULT_NOT_EXISTS = 18
    ERROR_FAILED_TO_SEND_TASK_COMMAND = 19
    ERROR_UNSUPPORTED_HTTP_METHOD = 20

    ERROR_TASK_ALREADY_EXISTS = 21
    ERROR_TASK_NOT_EXISTS = 22
    ERROR_MESSAGE_TARGET_NOT_EXISTS = 23
    ERROR_MESSAGE_DESERIALIZE_FAILED = 24
    ERROR_TASK_GROUP_NOT_EXISTS = 25
    ERROR_FAILED_TO_CALLBACK_MASTER = 26
    ERROR_UNRECOGNIZED_HEADER = 27

    ERROR_PARAMETER_MISSING_OR_INVALID = 28
    ERROR_WORKER_NOT_EXISTS = 29
    ERROR_CANNOT_CONNECT_TO_NAMENODE = 30
    ERROR_HTTP_CONNECTION_FAILED = 31
    ERROR_NO_WORKER_TO_BE_ASSIGNED = 32
    ERROR_TASK_HANDLER_NOT_EXISTS = 33
    ERROR_TICK_DATA_NOT_EXISTS_IN_OLD_DB = 34
    ERROR_TICK_STOCK_NOT_EXISTS = 35
    ERROR_TICK_DATA_NOT_EXISTS_IN_OLD_DB_ON_DAY = 36
    ERROR_TICK_RESULT_INCORRECT = 37
    ERROR_TASK_GROUP_IS_EMPTY = 38
    ERROR_TASK_HAS_NOTHING_TO_BE_DONE = 39
    ERROR_INVALID_STOCK_VIEW_NAME = 40
    ERROR_INVALID_STOCK_VIEW_RELATION = 41
    ERROR_TICK_STOCK_VIEW_NOT_EXISTS = 42
    ERROR_TICK_DATA_NOT_EXISTS = 43
    ERROR_TICK_DATA_NOT_EXISTS_ON_DAY = 46
    ERROR_TICK_DATA_NOT_AVAILABLE = 48
    ERROR_TICK_STOCK_VIEW_ALREADY_EXISTS = 49
    ERROR_INVALID_FACTOR_RESULT = 50
    ERROR_GROUP_FACTOR_NOT_EXISTS = 51
    ERROR_GROUP_FACTOR_SIGNATURE_NOT_MATCHED = 51
    ERROR_SUB_FACTOR_CONFLICT_WITH_OTHER_FACTOR = 52
    ERROR_GROUP_FACTOR_SOURCE_CONFLICT = 53
