class ProtoConf(object):
    COMMAND_HEADER = "<FACTOR_KEEPER_COMMAND>"
    WORKER_HEADER = "<FACTOR_KEEPER_WORKER>"
    CALLBACK_HEADER = "<FACTOR_KEEPER_CALLBACK>"
    RET_MSG_HEADER = "<FACTOR_KEEPER_RET_MSG>"

    TASK_SPLITTER = "$#$$#$"
    DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S"
